name: Build and Release Executables

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    name: Build Executable for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyftpdlib

      - name: Extract Version Tag
        shell: bash
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build Executable with PyInstaller
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            pyinstaller --onefile --windowed --name server_setup_windows_${{ env.VERSION }} server_setup.py
          elif [ "${{ runner.os }}" == "macOS" ]; then
            pyinstaller --onefile --windowed --name server_setup_macos_${{ env.VERSION }} server_setup.py
            # Remove unnecessary macOS files
            rm -f dist/*.icns dist/Info.plist
          else
            pyinstaller --onefile --name server_setup_linux_${{ env.VERSION }} server_setup.py
          fi

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: server_setup_${{ matrix.os }}_${{ env.VERSION }}
          path: dist/*

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: List Artifacts for Debugging
        run: ls -R ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          files: ./artifacts/**/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
