name: Build and Release Executables

# Trigger the workflow on push to tags or allow manual triggering
on:
  push:
    tags:
      - "v*.*.*"  # Trigger on version tags like "v1.0.0"
  workflow_dispatch:  # Allow manual triggering of the workflow from GitHub Actions UI

jobs:
  build:
    name: Build Executables for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyftpdlib

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --hidden-import=pyftpdlib.handlers \
                      --hidden-import=pyftpdlib.servers --hidden-import=pyftpdlib.authorizers \
                      server_setup.py
        shell: bash

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: server_setup_${{ matrix.os }}
          path: dist/*

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create Release and Upload Files
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./artifacts/**/* 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
